-- ============================================================
-- Fresko Cumbres · 03 · Equipos, roles simples y bitácora
-- ============================================================
-- Cambia el modelo de permisos de 4 banderas a 2 roles:
--   admin  -> entra al dashboard completo + todo lo de equipo
--   equipo -> solo /lista y /puestos (pasar lista, altas, datos, INE)
-- Agrega equipos (A-D con nombre editable), suplencias y bitácora privada.
-- ============================================================

-- ---------- 1. ROLES ----------
alter table dashboard_acceso add column if not exists rol text;
update dashboard_acceso set rol = case when admin then 'admin' else 'equipo' end where rol is null;
alter table dashboard_acceso alter column rol set default 'equipo';
alter table dashboard_acceso alter column rol set not null;
alter table dashboard_acceso drop constraint if exists dashboard_acceso_rol_chk;
alter table dashboard_acceso add constraint dashboard_acceso_rol_chk check (rol in ('admin','equipo'));

alter table invitaciones add column if not exists rol text;
update invitaciones set rol = case when admin then 'admin' else 'equipo' end where rol is null;
alter table invitaciones alter column rol set default 'equipo';
alter table invitaciones alter column rol set not null;
alter table invitaciones drop constraint if exists invitaciones_rol_chk;
alter table invitaciones add constraint invitaciones_rol_chk check (rol in ('admin','equipo'));

-- ---------- 2. EQUIPOS ----------
create table if not exists equipos (
  id          smallint generated by default as identity primary key,
  campana     text not null default 'FRESKO-CUMBRES-SEP26',
  clave       text not null,
  nombre      text not null,
  color       text,
  punto_clave text,
  activo      boolean not null default true,
  creado_en   timestamptz not null default now(),
  unique (campana, clave)
);

insert into equipos (clave, nombre, color) values
  ('A','Equipo A','#0B5D2E'),
  ('B','Equipo B','#F2681F'),
  ('C','Equipo C','#2E6FA3'),
  ('D','Equipo D','#8A4FBF')
on conflict (campana, clave) do nothing;

alter table candidatos add column if not exists equipo_id smallint references equipos(id) on delete set null;
create index if not exists idx_cand_equipo on candidatos(equipo_id);

-- ---------- 3. FOTO DE INE ----------
alter table candidatos add column if not exists foto_ine_path text;
alter table candidatos add column if not exists foto_ine_en   timestamptz;

-- ---------- 4. SUPLENCIAS ----------
create table if not exists suplencias (
  id             bigint generated always as identity primary key,
  campana        text not null default 'FRESKO-CUMBRES-SEP26',
  dia            date not null default ((now() at time zone 'America/Monterrey')::date),
  folio_ausente  text not null,
  folio_suplente text not null,
  equipo_id      smallint references equipos(id),
  motivo         text,
  creado_por     uuid,
  creado_en      timestamptz not null default now(),
  unique (campana, dia, folio_ausente)
);

-- ---------- 5. BITACORA (privada: sin políticas RLS, nadie la lee por API) ----------
create table if not exists bitacora (
  id            bigint generated always as identity primary key,
  momento       timestamptz not null default now(),
  actor         uuid,
  actor_correo  text,
  actor_nombre  text,
  accion        text not null,
  folio         text,
  detalle       jsonb not null default '{}'::jsonb
);
create index if not exists idx_bitacora_momento on bitacora(momento desc);
create index if not exists idx_bitacora_folio   on bitacora(folio);

alter table equipos    enable row level security;
alter table suplencias enable row level security;
alter table bitacora   enable row level security;

drop policy if exists equipos_lectura on equipos;
create policy equipos_lectura on equipos for select to authenticated using (true);
drop policy if exists suplencias_lectura on suplencias;
create policy suplencias_lectura on suplencias for select to authenticated using (true);
-- bitacora: intencionalmente sin políticas. Solo con service_role / SQL editor.

-- ---------- 6. HELPERS ----------
create or replace function public.es_admin() returns boolean
language sql stable security definer set search_path to 'public' as $fn$
  select coalesce((select rol = 'admin' from dashboard_acceso where user_id = auth.uid()), false);
$fn$;

create or replace function public.puede_lista() returns boolean
language sql stable security definer set search_path to 'public' as $fn$
  select exists (select 1 from dashboard_acceso where user_id = auth.uid());
$fn$;

create or replace function public.anotar(
  p_accion text, p_folio text default null, p_detalle jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path to 'public' as $fn$
declare v_correo text; v_nombre text;
begin
  select correo, nombre into v_correo, v_nombre from dashboard_acceso where user_id = auth.uid();
  insert into bitacora (actor, actor_correo, actor_nombre, accion, folio, detalle)
  values (auth.uid(), v_correo, v_nombre, p_accion, p_folio, coalesce(p_detalle,'{}'::jsonb));
end; $fn$;

revoke all on function public.anotar(text, text, jsonb) from public;
revoke all on function public.anotar(text, text, jsonb) from anon;
revoke all on function public.anotar(text, text, jsonb) from authenticated;

-- ---------- 7. PERMISOS (reescritos sobre rol) ----------
create or replace function public.mi_permiso(p_cual text) returns boolean
language sql stable security definer set search_path to 'public' as $fn$
  select case p_cual
           when 'admin'      then public.es_admin()
           when 'dinero'     then public.es_admin()
           when 'candidatos' then public.es_admin()
           when 'lista'      then public.puede_lista()
           else false
         end;
$fn$;

create or replace function public.mis_permisos() returns jsonb
language sql stable security definer set search_path to 'public' as $fn$
  select coalesce(
    (select jsonb_build_object(
        'nombre', nombre, 'correo', correo, 'rol', rol,
        'admin', rol = 'admin', 'lista', true,
        'candidatos', rol = 'admin', 'dinero', rol = 'admin')
     from dashboard_acceso where user_id = auth.uid()),
    jsonb_build_object('rol', null, 'admin', false, 'lista', false,
                       'candidatos', false, 'dinero', false));
$fn$;

create or replace function public.puede_ver_dashboard() returns boolean
language sql stable security definer set search_path to 'public' as $fn$
  select public.puede_lista();
$fn$;

create or replace function public.reclamar_primer_admin() returns jsonb
language plpgsql security definer set search_path to 'public' as $fn$
declare v_correo text;
begin
  if auth.uid() is null then raise exception 'SIN_SESION'; end if;
  if exists (select 1 from dashboard_acceso where rol = 'admin') then
    return jsonb_build_object('ok', false, 'motivo','YA_HAY_ADMIN');
  end if;
  select email into v_correo from auth.users where id = auth.uid();
  insert into dashboard_acceso (user_id, nombre, correo, rol, ver_candidatos, ver_dinero, pasar_lista, admin)
  values (auth.uid(), 'Administrador', v_correo, 'admin', true, true, true, true)
  on conflict (user_id) do update set rol = 'admin', admin = true,
       ver_dinero = true, pasar_lista = true, ver_candidatos = true,
       correo = coalesce(dashboard_acceso.correo, excluded.correo);
  perform public.anotar('primer_admin', null, jsonb_build_object('correo', v_correo));
  return jsonb_build_object('ok', true, 'correo', v_correo);
end; $fn$;

create or replace function public.crear_invitacion(p jsonb) returns jsonb
language plpgsql security definer set search_path to 'public' as $fn$
declare v_tok uuid; v_rol text := lower(coalesce(p->>'rol','equipo'));
begin
  if not public.es_admin() then raise exception 'SIN_PERMISO'; end if;
  if v_rol not in ('admin','equipo') then v_rol := 'equipo'; end if;
  insert into invitaciones (correo, nombre, rol, creada_por,
                            ver_candidatos, ver_dinero, pasar_lista, admin)
  values (lower(btrim(p->>'correo')), nullif(btrim(coalesce(p->>'nombre','')),''),
          v_rol, auth.uid(),
          v_rol = 'admin', v_rol = 'admin', true, v_rol = 'admin')
  returning token into v_tok;
  perform public.anotar('invitacion_creada', null,
    jsonb_build_object('correo', p->>'correo', 'rol', v_rol));
  return jsonb_build_object('ok', true, 'token', v_tok, 'rol', v_rol);
end; $fn$;

create or replace function public.ver_invitacion(p_token uuid) returns jsonb
language sql stable security definer set search_path to 'public' as $fn$
  select coalesce((select jsonb_build_object(
      'ok', usada_en is null and expira_en > now(),
      'correo', correo, 'nombre', nombre, 'rol', rol,
      'usada', usada_en is not null, 'vencida', expira_en <= now())
    from invitaciones where token = p_token),
    jsonb_build_object('ok', false, 'no_existe', true));
$fn$;

create or replace function public.aceptar_invitacion(p_token uuid) returns jsonb
language plpgsql security definer set search_path to 'public' as $fn$
declare v record; v_correo text;
begin
  if auth.uid() is null then raise exception 'SIN_SESION'; end if;
  select * into v from invitaciones where token = p_token;
  if v.token is null then return jsonb_build_object('ok', false, 'motivo','NO_EXISTE'); end if;
  if v.usada_en is not null then return jsonb_build_object('ok', false, 'motivo','YA_USADA'); end if;
  if v.expira_en <= now() then return jsonb_build_object('ok', false, 'motivo','VENCIDA'); end if;

  select email into v_correo from auth.users where id = auth.uid();
  if lower(v_correo) <> lower(v.correo) then
    return jsonb_build_object('ok', false, 'motivo','CORREO_DISTINTO', 'esperado', v.correo);
  end if;

  insert into dashboard_acceso (user_id, nombre, correo, rol,
                                ver_candidatos, ver_dinero, pasar_lista, admin)
  values (auth.uid(), v.nombre, v.correo, v.rol,
          v.rol = 'admin', v.rol = 'admin', true, v.rol = 'admin')
  on conflict (user_id) do update set
    nombre = excluded.nombre, correo = excluded.correo, rol = excluded.rol,
    ver_candidatos = excluded.ver_candidatos, ver_dinero = excluded.ver_dinero,
    pasar_lista = excluded.pasar_lista, admin = excluded.admin;

  update invitaciones set usada_en = now() where token = p_token;
  perform public.anotar('invitacion_aceptada', null,
    jsonb_build_object('correo', v.correo, 'rol', v.rol));
  return jsonb_build_object('ok', true, 'nombre', v.nombre, 'rol', v.rol);
end; $fn$;
