-- 12 · Un solo libro de jornadas, y /pase sigue a la campaña activa
--
-- Quedaron dos tablas registrando lo mismo: `asistencia` (Etapa 1, la
-- pasa el coordinador) y `presencia` (Etapa 2, la marca la persona con
-- GPS). Con las dos vivas, los pagos de una etapa no veían la
-- asistencia de la otra.
--
-- `v_jornadas` las une, y de ahí leen los pagos y el pase de lista.
--
-- /pase deja de asumir la Etapa 1: la plantilla ya no son "los que
-- fueron a la capacitación" sino los inscritos de la campaña abierta.
--
-- Las marcas del coordinador se guardan en `presencia` con origen
-- 'pase_lista'. Cuentan para el pago del día pero NO para el bono de
-- puntualidad: ese lo gana la persona marcando desde su teléfono, en
-- el punto y en hora. Si no, bastaría con que el coordinador pasara
-- lista tarde para regalar o quitar bonos.
--
-- Las definiciones vigentes se aplicaron por migración:
--   un_solo_libro_de_jornadas
--   pase_lista_por_campana_activa

-- ------------------------------------------------------------
-- Reglas de checada de la Etapa 2 (migración ventanas_de_checada_etapa2)
--
--   Entrada: desde la 1:00 pm, una hora de margen. Después ya no deja.
--   Salida:  nunca antes de las 7:00 pm.
--
-- A la gente se le dice "30 minutos de tolerancia"; el margen real es
-- de 60, a propósito, para no castigar al que se atrasó tantito.
--
-- Si la marca se acepta, es puntual: la ventana ES la puntualidad.
-- Así nadie tiene que explicar por qué algo quedó registrado pero no
-- contó.
--
-- `bono_dia` guarda los días acreditados a mano, con su motivo. Se usó
-- el 14 de septiembre: fue el primer día y se les explicó el sistema
-- sobre la marcha, así que la asistencia bastó.
