-- 13 · Misiones del día y panel de la Etapa 2
--
-- Aplicado por las migraciones:
--   misiones_del_dia            tabla `misiones` + mision_del_dia() /
--                               misiones_lista() / guardar_mision()
--   resumen_etapa2              todo lo del día en una sola llamada
--   v_confirmacion_trabajo_y_etapa
--                               agrega dias_trabajados y en_etapa2, para
--                               poder convocar solo a quien sí trabajó
--
-- La misión se escribe con anticipación y queda en borrador: nadie la
-- ve hasta que se marca como publicada. `mision_del_dia()` es la única
-- de estas funciones abierta al público, y solo devuelve la de hoy y
-- solo si está publicada.

-- ------------------------------------------------------------
-- Titulares, suplentes y refuerzos (titulares_suplentes_y_refuerzos)
--
-- 15 titulares, 2 suplentes, el resto a refuerzos. El lugar no se
-- pide: lo decide `v_prioridad_etapa2` con tres criterios, en peso:
--
--   1. Quien estuvo el 14 de septiembre, el primer día.
--   2. Quien ya trabajó antes, en la Etapa 1 (y cuántos días).
--   3. Quien se registró primero.
--
-- Los tres son hechos ya ocurridos, así que el orden no se mueve
-- solo. Alguien nuevo solo sube si trabajó antes, que es justo lo
-- que se quiere premiar.
--
-- `candidatos.disponible_refuerzo` sale de una casilla del registro:
-- acepta quedar en refuerzos y que se le avise CON UN DÍA DE
-- ANTICIPACIÓN, nunca a última hora.

-- ------------------------------------------------------------
-- La fila completa (prioridad_completa_y_reserva_v2)
--
-- `v_prioridad_etapa2` ahora cubre a TODOS los que tienen folio, no
-- solo a los inscritos: si se abre una vacante hay que saber a quién
-- llamar aunque no se haya reinscrito.
--
-- Orden: 1) se presentó el primer día, 2) ya trabajó antes,
--        3) ya está inscrito, 4) llegó primero.
--
-- `mi_lugar(folio, tel4)` es lo que cada quien consulta de sí mismo
-- en /milugar, sin contraseña. A nadie se le dice "no": se le dice
-- que por ahora está cubierto y que sigue en la fila para vacantes,
-- suplencias y las activaciones que vienen.
